function varargout = plot_map(lat_arr, long_arr, value_matrix, title_str, cbar_str, cmap_name)
% PLOT_MAP plots map of property over lunar surface. Use one argument
% specifying file path of data file (generated by generate_map) to plot map
% of.
%
% varargout = PLOT_MAP(lat_arr, long_arr, value_matrix, title_str,
% cbar_str, cmap_name)

if nargin < 4
    title_str = '';
end
if nargin < 5
    cbar_str = '';
end
if nargin < 6
    cmap_name = 'viridis';
end
if nargin == 1
    data_path = lat_arr;
    data_from_file = load(data_path);
    data = data_from_file.data;
    lat_arr = data.lat_arr;
    long_arr = data.long_arr;
    value_matrix = data.value_matrix;
    title_str = data.plot_title;
    cbar_str = data.plot_label;
end

if ~ischar(title_str)
    title_str{2} = strcat('{\rm\color{gray}\fontsize{8}', title_str{2}, '}');
end

clf
colormap(cmap_name);
axesm('robinson', 'Grid', 'on'); %! use mollweid?
fig = gcf;
fig.PaperUnits = 'inches';
fig.PaperPosition = [0 0 12 6];
ax = gca;
outerpos = ax.OuterPosition;
ti = ax.TightInset; 
margin = 0.05;
left = outerpos(1) + ti(1) + margin;
bottom = outerpos(2) + ti(2) + margin;
ax_width = outerpos(3) - ti(1) - ti(3) - 2*margin;
ax_height = outerpos(4) - ti(2) - ti(4) - 2*margin;
ax.Position = [left bottom ax_width ax_height];
plot_h = pcolorm(lat_arr, long_arr, value_matrix);
c = contourcbar;
c.Label.String = cbar_str;
title(title_str)
drawnow

if nargout > 0
    [varargout{1:nargout}] = plot_h;
end

end
